<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AcademicManagementController;
use App\Http\Controllers\AcademicSessionController;
use App\Http\Controllers\BursaryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PrefectRoleController;
use App\Http\Controllers\StudentRoleController;
use App\Http\Controllers\TrafficAnalyticsController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboard;
use App\Http\Controllers\CBT\DashboardController as CBTDashboard;
use App\Http\Controllers\CBT\ExamController as CBTExamController;
use App\Http\Controllers\CBT\MonitorController as CBTMonitorController;
use App\Http\Controllers\HOD\DashboardController as HODDashboard;
use App\Http\Controllers\HOD\ExamController as HODExamController;
use App\Http\Controllers\HOD\OverrideController as HODOverrideController;
use App\Http\Controllers\HOD\StudentController as HODStudentController;
use App\Http\Controllers\LessonNoteReviewController;
use App\Http\Controllers\Prefect\DashboardController as PrefectDashboard;
use App\Http\Controllers\Prefect\StudentController as PrefectStudentController;
use App\Http\Controllers\Student\ExerciseController as StudentExerciseController;
use App\Http\Controllers\Student\DirectoryController as StudentDirectoryController;
use App\Http\Controllers\Student\DashboardController as StudentDashboard;
use App\Http\Controllers\Student\ExamController as StudentExamController;
use App\Http\Controllers\Student\LessonNoteController as StudentLessonNoteController;
use App\Http\Controllers\Student\ProfileController as StudentProfileController;
use App\Http\Controllers\Student\RequestController as StudentRequestController;
use App\Http\Controllers\Teacher\AttendanceController as TeacherAttendanceController;
use App\Http\Controllers\Teacher\ClassController as TeacherClassController;
use App\Http\Controllers\Teacher\DashboardController as TeacherDashboard;
use App\Http\Controllers\Teacher\ExamController as TeacherExamController;
use App\Http\Controllers\Teacher\ExerciseQuestionController as TeacherExerciseQuestionController;
use App\Http\Controllers\Teacher\ExerciseSubmissionController as TeacherExerciseSubmissionController;
use App\Http\Controllers\Teacher\LessonNoteController as TeacherLessonNoteController;
use App\Http\Controllers\Teacher\LessonExerciseController as TeacherLessonExerciseController;
use App\Http\Controllers\Teacher\QuestionController as TeacherQuestionController;
use App\Http\Controllers\Teacher\ResultController as TeacherResultController;
use App\Http\Controllers\Teacher\ProfileController as TeacherProfileController;
use App\Http\Controllers\Teacher\PromotionController as TeacherPromotionController;
use App\Http\Controllers\Teacher\StudentController as TeacherStudentController;
use App\Http\Controllers\Teacher\AIQuestionController as TeacherAIQuestionController;

// Authentication Routes
Route::view('privacy-policy', 'privacy-policy')->name('privacy.policy');

Route::middleware('guest')->group(function () {
    Route::get('/', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/', [LoginController::class, 'login'])->name('login.submit');
});

Route::post('logout', [LoginController::class, 'logout'])->name('logout')->middleware('auth');

// Password change routes
Route::middleware('auth')->group(function () {
    Route::get('password/change', [ChangePasswordController::class, 'showChangeForm'])->name('password.change');
    Route::post('password/change', [ChangePasswordController::class, 'change'])->name('password.change.submit');
});

// Admin Routes
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('dashboard', [AdminDashboard::class, 'index'])->name('dashboard');
    Route::get('lesson-notes', [LessonNoteReviewController::class, 'index'])->name('lesson-notes.index');
    Route::get('lesson-notes/archives', [LessonNoteReviewController::class, 'archives'])->name('lesson-notes.archives');
    Route::get('lesson-notes/{lessonNote}', [LessonNoteReviewController::class, 'show'])->name('lesson-notes.show');
    Route::post('lesson-notes/{lessonNote}/approve', [LessonNoteReviewController::class, 'approve'])->name('lesson-notes.approve');
    Route::post('lesson-notes/{lessonNote}/return', [LessonNoteReviewController::class, 'return'])->name('lesson-notes.return');
    Route::post('lesson-notes/{lessonNote}/reject', [LessonNoteReviewController::class, 'reject'])->name('lesson-notes.reject');
    Route::post('lesson-notes/{lessonNote}/archive', [LessonNoteReviewController::class, 'archive'])->name('lesson-notes.archive');
    Route::post('lesson-notes/{lessonNote}/restore', [LessonNoteReviewController::class, 'restore'])->name('lesson-notes.restore');
    Route::delete('lesson-notes/{lessonNote}', [LessonNoteReviewController::class, 'destroy'])->name('lesson-notes.destroy');
    Route::get('users', [AdminDashboard::class, 'users'])->name('users');
    Route::post('users', [AdminDashboard::class, 'storeAdminUser'])->name('users.store');
    Route::put('users/{user}/role', [AdminDashboard::class, 'updateUserRole'])->name('users.role.update');
    Route::get('students', [UserManagementController::class, 'students'])->name('students');
    Route::post('students', [UserManagementController::class, 'storeStudent'])->name('students.store');
    Route::put('students/{student}', [UserManagementController::class, 'updateStudent'])->name('students.update');
    Route::delete('students/{student}', [UserManagementController::class, 'destroyStudent'])->name('students.destroy');
    Route::get('staff', [UserManagementController::class, 'staff'])->name('staff');
    Route::post('staff', [UserManagementController::class, 'storeStaff'])->name('staff.store');
    Route::put('staff/{staff}', [UserManagementController::class, 'updateStaff'])->name('staff.update');
    Route::delete('staff/{staff}', [UserManagementController::class, 'destroyStaff'])->name('staff.destroy');
    Route::post('staff/{staff}/classes', [UserManagementController::class, 'assignClass'])->name('staff.classes.assign');
    Route::delete('staff/{staff}/classes/{class}', [UserManagementController::class, 'unassignClass'])->name('staff.classes.unassign');
    Route::get('classes', [AcademicManagementController::class, 'classes'])->name('classes');
    Route::post('classes', [AcademicManagementController::class, 'storeClass'])->name('classes.store');
    Route::put('classes/{class}', [AcademicManagementController::class, 'updateClass'])->name('classes.update');
    Route::delete('classes/{class}', [AcademicManagementController::class, 'destroyClass'])->name('classes.destroy');
    Route::get('subjects', [AcademicManagementController::class, 'subjects'])->name('subjects');
    Route::post('subjects', [AcademicManagementController::class, 'storeSubject'])->name('subjects.store');
    Route::delete('subjects/group', [AcademicManagementController::class, 'destroySubjectGroup'])->name('subjects.group.destroy');
    Route::put('subjects/{subject}', [AcademicManagementController::class, 'updateSubject'])->name('subjects.update');
    Route::delete('subjects/{subject}', [AcademicManagementController::class, 'destroySubject'])->name('subjects.destroy');
    Route::get('exams', [AdminDashboard::class, 'exams'])->name('exams');
    Route::get('exams/create', [AdminDashboard::class, 'examCreate'])->name('exams.create');
    Route::post('exams/store', [AdminDashboard::class, 'examStore'])->name('exams.store');
    Route::get('exams/{exam}', [AdminDashboard::class, 'examShow'])->name('exams.show');
    Route::get('exams/{exam}/edit', [AdminDashboard::class, 'examEdit'])->name('exams.edit');
    Route::put('exams/{exam}', [AdminDashboard::class, 'examUpdate'])->name('exams.update');
    Route::delete('exams/{exam}', [AdminDashboard::class, 'examDestroy'])->name('exams.destroy');
    Route::post('exams/{exam}/toggle-live', [AdminDashboard::class, 'toggleExamLive'])->name('exams.toggle-live');
    Route::post('exams/{exam}/generate-questions', [AdminDashboard::class, 'generateQuestions'])->name('exams.generate-questions');
    Route::post('exams/{exam}/add-question', [AdminDashboard::class, 'addManualQuestion'])->name('exams.add-question');
    Route::delete('exam-questions/{question}', [AdminDashboard::class, 'deleteQuestion'])->name('exam-questions.delete');
    Route::delete('questions/{question}', [AdminDashboard::class, 'questionDestroy'])->name('questions.destroy');
    Route::get('monitor', [CBTMonitorController::class, 'index'])->name('monitor');
    Route::get('monitor/data', [CBTMonitorController::class, 'data'])->name('monitor.data');
    Route::get('payments', [BursaryController::class, 'index'])->name('payments');
    Route::get('payments/students/{student}', [BursaryController::class, 'showStudent'])->name('payments.students.show');
    Route::post('payments/fees', [BursaryController::class, 'storeFee'])->name('payments.fees.store');
    Route::patch('payments/fees/{feeItem}/toggle', [BursaryController::class, 'toggleFee'])->name('payments.fees.toggle');
    Route::delete('payments/fees/{feeItem}', [BursaryController::class, 'destroyFee'])->name('payments.fees.destroy');
    Route::put('payments/students/{student}', [BursaryController::class, 'recordPayment'])->name('payments.students.update');
    Route::post('payments/students/{student}/optional-fees/{feeItem}/remove', [BursaryController::class, 'removeOptionalFee'])->name('payments.optional-fees.remove');
    Route::delete('payments/students/{student}/optional-fees/{feeItem}/restore', [BursaryController::class, 'restoreOptionalFee'])->name('payments.optional-fees.restore');
    Route::get('overrides', [HODOverrideController::class, 'index'])->name('overrides');
    Route::post('overrides', [HODOverrideController::class, 'store'])->name('overrides.store');
    Route::delete('overrides/{override}', [HODOverrideController::class, 'destroy'])->name('overrides.destroy');
    Route::get('reports', [AdminDashboard::class, 'reports'])->name('reports');
    Route::get('settings', [AdminDashboard::class, 'settings'])->name('settings');
    Route::post('settings/update', [AdminDashboard::class, 'updateSettings'])->name('settings.update');
    Route::get('profile', [TeacherProfileController::class, 'edit'])->name('profile.edit');
    Route::put('profile', [TeacherProfileController::class, 'update'])->name('profile.update');
});

// HOD Routes
Route::middleware(['auth', 'role:hod'])->prefix('hod')->name('hod.')->group(function () {
    Route::get('dashboard', [HODDashboard::class, 'index'])->name('dashboard');
    Route::get('lesson-notes', [LessonNoteReviewController::class, 'index'])->name('lesson-notes.index');
    Route::get('lesson-notes/archives', [LessonNoteReviewController::class, 'archives'])->name('lesson-notes.archives');
    Route::get('lesson-notes/{lessonNote}', [LessonNoteReviewController::class, 'show'])->name('lesson-notes.show');
    Route::post('lesson-notes/{lessonNote}/approve', [LessonNoteReviewController::class, 'approve'])->name('lesson-notes.approve');
    Route::post('lesson-notes/{lessonNote}/return', [LessonNoteReviewController::class, 'return'])->name('lesson-notes.return');
    Route::post('lesson-notes/{lessonNote}/reject', [LessonNoteReviewController::class, 'reject'])->name('lesson-notes.reject');
    Route::post('lesson-notes/{lessonNote}/archive', [LessonNoteReviewController::class, 'archive'])->name('lesson-notes.archive');
    Route::post('lesson-notes/{lessonNote}/restore', [LessonNoteReviewController::class, 'restore'])->name('lesson-notes.restore');
    Route::delete('lesson-notes/{lessonNote}', [LessonNoteReviewController::class, 'destroy'])->name('lesson-notes.destroy');
    Route::get('exams', [HODExamController::class, 'index'])->name('exams');
    Route::get('students', [UserManagementController::class, 'students'])->name('students');
    Route::post('students', [UserManagementController::class, 'storeStudent'])->name('students.store');
    Route::put('students/{student}', [UserManagementController::class, 'updateStudent'])->name('students.update');
    Route::delete('students/{student}', [UserManagementController::class, 'destroyStudent'])->name('students.destroy');
    Route::get('staff', [UserManagementController::class, 'staff'])->name('staff');
    Route::post('staff', [UserManagementController::class, 'storeStaff'])->name('staff.store');
    Route::put('staff/{staff}', [UserManagementController::class, 'updateStaff'])->name('staff.update');
    Route::delete('staff/{staff}', [UserManagementController::class, 'destroyStaff'])->name('staff.destroy');
    Route::post('staff/{staff}/classes', [UserManagementController::class, 'assignClass'])->name('staff.classes.assign');
    Route::delete('staff/{staff}/classes/{class}', [UserManagementController::class, 'unassignClass'])->name('staff.classes.unassign');
    Route::get('classes', [AcademicManagementController::class, 'classes'])->name('classes');
    Route::post('classes', [AcademicManagementController::class, 'storeClass'])->name('classes.store');
    Route::put('classes/{class}', [AcademicManagementController::class, 'updateClass'])->name('classes.update');
    Route::delete('classes/{class}', [AcademicManagementController::class, 'destroyClass'])->name('classes.destroy');
    Route::get('subjects', [AcademicManagementController::class, 'subjects'])->name('subjects');
    Route::post('subjects', [AcademicManagementController::class, 'storeSubject'])->name('subjects.store');
    Route::delete('subjects/group', [AcademicManagementController::class, 'destroySubjectGroup'])->name('subjects.group.destroy');
    Route::put('subjects/{subject}', [AcademicManagementController::class, 'updateSubject'])->name('subjects.update');
    Route::delete('subjects/{subject}', [AcademicManagementController::class, 'destroySubject'])->name('subjects.destroy');
    Route::get('payments', [BursaryController::class, 'index'])->name('payments');
    Route::get('payments/students/{student}', [BursaryController::class, 'showStudent'])->name('payments.students.show');
    Route::post('payments/fees', [BursaryController::class, 'storeFee'])->name('payments.fees.store');
    Route::patch('payments/fees/{feeItem}/toggle', [BursaryController::class, 'toggleFee'])->name('payments.fees.toggle');
    Route::delete('payments/fees/{feeItem}', [BursaryController::class, 'destroyFee'])->name('payments.fees.destroy');
    Route::put('payments/students/{student}', [BursaryController::class, 'recordPayment'])->name('payments.students.update');
    Route::post('payments/students/{student}/optional-fees/{feeItem}/remove', [BursaryController::class, 'removeOptionalFee'])->name('payments.optional-fees.remove');
    Route::delete('payments/students/{student}/optional-fees/{feeItem}/restore', [BursaryController::class, 'restoreOptionalFee'])->name('payments.optional-fees.restore');
    Route::get('exams/create', [CBTExamController::class, 'create'])->name('exams.create');
    Route::post('exams', [CBTExamController::class, 'store'])->name('exams.store');
    Route::get('exams/{exam}', [CBTExamController::class, 'show'])->name('exams.show');
    Route::get('exams/{exam}/edit', [CBTExamController::class, 'edit'])->name('exams.edit');
    Route::put('exams/{exam}', [CBTExamController::class, 'update'])->name('exams.update');
    Route::delete('exams/{exam}', [CBTExamController::class, 'destroy'])->name('exams.destroy');
    Route::post('exams/{exam}/toggle', [CBTExamController::class, 'toggleLive'])->name('exams.toggle');
    Route::post('exams/{exam}/toggle-live', [CBTExamController::class, 'toggleLive'])->name('exams.toggle-live');
    Route::post('exams/{exam}/toggle-results', [CBTExamController::class, 'toggleResults'])->name('exams.toggle-results');
    Route::post('exams/{exam}/generate-questions', [CBTExamController::class, 'generateQuestions'])->name('exams.generate-questions');
    Route::post('exams/{exam}/add-question', [CBTExamController::class, 'addManualQuestion'])->name('exams.add-question');
    Route::delete('exam-questions/{question}', [CBTExamController::class, 'deleteQuestion'])->name('exam-questions.delete');
    Route::get('monitor', [CBTMonitorController::class, 'index'])->name('monitor');
    Route::get('monitor/data', [CBTMonitorController::class, 'data'])->name('monitor.data');
    Route::get('results', [TeacherResultController::class, 'index'])->name('results');
    Route::get('results/{exam}', [TeacherResultController::class, 'show'])->name('results.show');
    Route::post('results/{exam}/export', [TeacherResultController::class, 'export'])->name('results.export');
    Route::delete('results/{exam}/attempts/{attempt}/retake', [TeacherResultController::class, 'allowRetake'])->name('results.retakes.allow');
    Route::get('overrides', [HODOverrideController::class, 'index'])->name('overrides');
    Route::post('overrides', [HODOverrideController::class, 'store'])->name('overrides.store');
    Route::delete('overrides/{override}', [HODOverrideController::class, 'destroy'])->name('overrides.destroy');
    Route::get('profile', [TeacherProfileController::class, 'edit'])->name('profile.edit');
    Route::put('profile', [TeacherProfileController::class, 'update'])->name('profile.update');
});

// CBT Personnel Routes
Route::middleware(['auth', 'role:cbt_personnel'])->prefix('cbt')->name('cbt.')->group(function () {
    Route::get('dashboard', [CBTDashboard::class, 'index'])->name('dashboard');
    Route::get('students', [UserManagementController::class, 'students'])->name('students');
    Route::post('students', [UserManagementController::class, 'storeStudent'])->name('students.store');
    Route::put('students/{student}', [UserManagementController::class, 'updateStudent'])->name('students.update');
    Route::delete('students/{student}', [UserManagementController::class, 'destroyStudent'])->name('students.destroy');
    Route::get('exams', [CBTExamController::class, 'index'])->name('exams');
    Route::get('exams/create', [CBTExamController::class, 'create'])->name('exams.create');
    Route::post('exams', [CBTExamController::class, 'store'])->name('exams.store');
    Route::get('exams/{exam}', [CBTExamController::class, 'show'])->name('exams.show');
    Route::get('exams/{exam}/edit', [CBTExamController::class, 'edit'])->name('exams.edit');
    Route::put('exams/{exam}', [CBTExamController::class, 'update'])->name('exams.update');
    Route::delete('exams/{exam}', [CBTExamController::class, 'destroy'])->name('exams.destroy');
    Route::post('exams/{exam}/toggle', [CBTExamController::class, 'toggleLive'])->name('exams.toggle');
    Route::post('exams/{exam}/toggle-live', [CBTExamController::class, 'toggleLive'])->name('exams.toggle-live');
    Route::post('exams/{exam}/toggle-results', [CBTExamController::class, 'toggleResults'])->name('exams.toggle-results');
    Route::post('exams/{exam}/generate-questions', [CBTExamController::class, 'generateQuestions'])->name('exams.generate-questions');
    Route::post('exams/{exam}/add-question', [CBTExamController::class, 'addManualQuestion'])->name('exams.add-question');
    Route::delete('exam-questions/{question}', [CBTExamController::class, 'deleteQuestion'])->name('exam-questions.delete');
    Route::get('monitor', [CBTMonitorController::class, 'index'])->name('monitor');
    Route::get('monitor/data', [CBTMonitorController::class, 'data'])->name('monitor.data');
    Route::get('results', [TeacherResultController::class, 'index'])->name('results');
    Route::get('results/{exam}', [TeacherResultController::class, 'show'])->name('results.show');
    Route::post('results/{exam}/export', [TeacherResultController::class, 'export'])->name('results.export');
    Route::delete('results/{exam}/attempts/{attempt}/retake', [TeacherResultController::class, 'allowRetake'])->name('results.retakes.allow');
    Route::get('payments', [BursaryController::class, 'index'])->name('payments');
    Route::get('payments/students/{student}', [BursaryController::class, 'showStudent'])->name('payments.students.show');
    Route::post('payments/fees', [BursaryController::class, 'storeFee'])->name('payments.fees.store');
    Route::patch('payments/fees/{feeItem}/toggle', [BursaryController::class, 'toggleFee'])->name('payments.fees.toggle');
    Route::delete('payments/fees/{feeItem}', [BursaryController::class, 'destroyFee'])->name('payments.fees.destroy');
    Route::put('payments/students/{student}', [BursaryController::class, 'recordPayment'])->name('payments.students.update');
    Route::post('payments/students/{student}/optional-fees/{feeItem}/remove', [BursaryController::class, 'removeOptionalFee'])->name('payments.optional-fees.remove');
    Route::delete('payments/students/{student}/optional-fees/{feeItem}/restore', [BursaryController::class, 'restoreOptionalFee'])->name('payments.optional-fees.restore');
    Route::get('overrides', [HODOverrideController::class, 'index'])->name('overrides');
    Route::post('overrides', [HODOverrideController::class, 'store'])->name('overrides.store');
    Route::delete('overrides/{override}', [HODOverrideController::class, 'destroy'])->name('overrides.destroy');
    Route::get('profile', [TeacherProfileController::class, 'edit'])->name('profile.edit');
    Route::put('profile', [TeacherProfileController::class, 'update'])->name('profile.update');
});

// Teacher Routes
Route::middleware(['auth', 'role:teacher'])->prefix('teacher')->name('teacher.')->group(function () {
    Route::get('dashboard', [TeacherDashboard::class, 'index'])->name('dashboard');
    Route::get('lesson-notes', [TeacherLessonNoteController::class, 'index'])->name('lesson-notes.index');
    Route::get('lesson-notes/create', [TeacherLessonNoteController::class, 'create'])->name('lesson-notes.create');
    Route::post('lesson-notes', [TeacherLessonNoteController::class, 'store'])->name('lesson-notes.store');
    Route::post('lesson-notes/inline-image', [TeacherLessonNoteController::class, 'uploadInlineImage'])->name('lesson-notes.inline-image');
    Route::post('lesson-notes/ai-draft', [TeacherLessonNoteController::class, 'generateAiDraft'])->name('lesson-notes.ai-draft');
    Route::post('lesson-notes/pdf-draft', [TeacherLessonNoteController::class, 'generateDraftFromPdf'])->name('lesson-notes.pdf-draft');
    Route::post('lesson-notes/continue-draft', [TeacherLessonNoteController::class, 'continueAiDraft'])->name('lesson-notes.continue-draft');
    Route::post('lesson-notes/exercise-draft', [TeacherLessonNoteController::class, 'generateExerciseDraft'])->name('lesson-notes.exercise-draft');
    Route::get('lesson-notes/{lessonNote}', [TeacherLessonNoteController::class, 'show'])->name('lesson-notes.show');
    Route::get('lesson-notes/{lessonNote}/edit', [TeacherLessonNoteController::class, 'edit'])->name('lesson-notes.edit');
    Route::put('lesson-notes/{lessonNote}', [TeacherLessonNoteController::class, 'update'])->name('lesson-notes.update');
    Route::post('lesson-notes/{lessonNote}/submit', [TeacherLessonNoteController::class, 'submit'])->name('lesson-notes.submit');
    Route::post('lesson-notes/{lessonNote}/withdraw', [TeacherLessonNoteController::class, 'withdraw'])->name('lesson-notes.withdraw');
    Route::delete('lesson-notes/{lessonNote}/attachments/{attachment}', [TeacherLessonNoteController::class, 'destroyAttachment'])->name('lesson-notes.attachments.destroy');
    Route::get('lesson-notes/{lessonNote}/exercise', [TeacherLessonExerciseController::class, 'show'])->name('lesson-notes.exercise.show');
    Route::post('lesson-notes/{lessonNote}/questions', [TeacherExerciseQuestionController::class, 'store'])->name('lesson-notes.questions.store');
    Route::post('lesson-notes/{lessonNote}/questions/ai-generate', [TeacherExerciseQuestionController::class, 'generateWithAi'])->name('lesson-notes.questions.ai-generate');
    Route::put('lesson-notes/{lessonNote}/questions/{question}', [TeacherExerciseQuestionController::class, 'update'])->name('lesson-notes.questions.update');
    Route::delete('lesson-notes/{lessonNote}/questions/{question}', [TeacherExerciseQuestionController::class, 'destroy'])->name('lesson-notes.questions.destroy');
    Route::get('exercises/{lessonExercise}/submissions', [TeacherExerciseSubmissionController::class, 'index'])->name('exercises.submissions.index');
    Route::get('exercises/{lessonExercise}/submissions/{attempt}/mark', [TeacherExerciseSubmissionController::class, 'edit'])->name('exercises.submissions.mark');
    Route::put('exercises/{lessonExercise}/submissions/{attempt}', [TeacherExerciseSubmissionController::class, 'update'])->name('exercises.submissions.update');
    Route::delete('exercises/{lessonExercise}/submissions/{attempt}', [TeacherExerciseSubmissionController::class, 'destroy'])->name('exercises.submissions.destroy');
    Route::post('exercises/{lessonExercise}/students/{student}/retry', [TeacherExerciseSubmissionController::class, 'grantRetry'])->name('exercises.retry');
    Route::get('classes', [TeacherClassController::class, 'index'])->name('classes');
    Route::get('students', [TeacherStudentController::class, 'index'])->name('students');
    Route::post('students', [UserManagementController::class, 'storeStudent'])->name('students.store');
    Route::put('students/{student}', [UserManagementController::class, 'updateStudent'])->name('students.update');
    Route::delete('students/{student}', [UserManagementController::class, 'destroyStudent'])->name('students.destroy');
    Route::get('exams', [TeacherExamController::class, 'index'])->name('exams');
    Route::get('exams/create', [TeacherExamController::class, 'create'])->name('exams.create');
    Route::post('exams', [TeacherExamController::class, 'store'])->name('exams.store');
    Route::get('exams/{exam}', [TeacherExamController::class, 'show'])->name('exams.show');
    Route::get('exams/{exam}/edit', [TeacherExamController::class, 'edit'])->name('exams.edit');
    Route::put('exams/{exam}', [TeacherExamController::class, 'update'])->name('exams.update');
    Route::delete('exams/{exam}', [TeacherExamController::class, 'destroy'])->name('exams.destroy');
    Route::post('exams/{exam}/toggle-live', [TeacherExamController::class, 'toggleLive'])->name('exams.toggle-live');
    Route::post('exams/{exam}/toggle-results', [TeacherExamController::class, 'toggleResults'])->name('exams.toggle-results');
    Route::post('exams/{exam}/generate-questions', [TeacherExamController::class, 'generateQuestions'])->name('exams.generate-questions');
    Route::post('exams/{exam}/add-question', [TeacherExamController::class, 'addManualQuestion'])->name('exams.add-question');
    Route::delete('exam-questions/{question}', [TeacherExamController::class, 'deleteQuestion'])->name('exam-questions.delete');
    Route::get('questions', [TeacherQuestionController::class, 'index'])->name('questions');
    Route::get('questions/create', [TeacherQuestionController::class, 'create'])->name('questions.create');
    Route::post('questions', [TeacherQuestionController::class, 'store'])->name('questions.store');
    Route::get('questions/{question}/edit', [TeacherQuestionController::class, 'edit'])->name('questions.edit');
    Route::put('questions/{question}', [TeacherQuestionController::class, 'update'])->name('questions.update');
    Route::delete('questions/{question}', [TeacherQuestionController::class, 'destroy'])->name('questions.destroy');
    Route::get('ai-questions', [TeacherAIQuestionController::class, 'index'])->name('ai-questions.index');
    Route::post('ai-questions/generate', [TeacherAIQuestionController::class, 'generate'])->name('ai-questions.generate');
    Route::get('ai-questions/exam/{examId}/questions', [TeacherAIQuestionController::class, 'getExamQuestions'])->name('ai-questions.exam-questions');
    Route::get('attendance', [TeacherAttendanceController::class, 'index'])->name('attendance');
    Route::post('attendance', [TeacherAttendanceController::class, 'store'])->name('attendance.store');
    Route::get('promotions', [TeacherPromotionController::class, 'index'])->name('promotions');
    Route::patch('promotions/{student}/promote', [TeacherPromotionController::class, 'promote'])->name('promotions.promote');
    Route::patch('promotions/{student}/demote', [TeacherPromotionController::class, 'demote'])->name('promotions.demote');
    Route::get('results', [TeacherResultController::class, 'index'])->name('results');
    Route::get('results/{exam}', [TeacherResultController::class, 'show'])->name('results.show');
    Route::post('results/{exam}/export', [TeacherResultController::class, 'export'])->name('results.export');
    Route::delete('results/{exam}/attempts/{attempt}/retake', [TeacherResultController::class, 'allowRetake'])->name('results.retakes.allow');
    Route::get('payments', [BursaryController::class, 'index'])->name('payments');
    Route::get('payments/students/{student}', [BursaryController::class, 'showStudent'])->name('payments.students.show');
    Route::post('payments/fees', [BursaryController::class, 'storeFee'])->name('payments.fees.store');
    Route::patch('payments/fees/{feeItem}/toggle', [BursaryController::class, 'toggleFee'])->name('payments.fees.toggle');
    Route::delete('payments/fees/{feeItem}', [BursaryController::class, 'destroyFee'])->name('payments.fees.destroy');
    Route::put('payments/students/{student}', [BursaryController::class, 'recordPayment'])->name('payments.students.update');
    Route::post('payments/students/{student}/optional-fees/{feeItem}/remove', [BursaryController::class, 'removeOptionalFee'])->name('payments.optional-fees.remove');
    Route::delete('payments/students/{student}/optional-fees/{feeItem}/restore', [BursaryController::class, 'restoreOptionalFee'])->name('payments.optional-fees.restore');
    Route::get('overrides', [HODOverrideController::class, 'index'])->name('overrides');
    Route::post('overrides', [HODOverrideController::class, 'store'])->name('overrides.store');
    Route::delete('overrides/{override}', [HODOverrideController::class, 'destroy'])->name('overrides.destroy');
    Route::get('profile', [TeacherProfileController::class, 'edit'])->name('profile.edit');
    Route::put('profile', [TeacherProfileController::class, 'update'])->name('profile.update');
});

// Prefect Routes
Route::middleware(['auth', 'role:prefect'])->prefix('prefect')->name('prefect.')->group(function () {
    Route::get('dashboard', [PrefectDashboard::class, 'index'])->name('dashboard');
    Route::get('lesson-notes', [StudentLessonNoteController::class, 'index'])->name('lesson-notes.index');
    Route::get('lesson-notes/{lessonNote}', [StudentLessonNoteController::class, 'show'])->name('lesson-notes.show');
    Route::get('exercises', [StudentExerciseController::class, 'index'])->name('exercises.index');
    Route::get('exercises/{lessonExercise}', [StudentExerciseController::class, 'show'])->name('exercises.show');
    Route::post('exercises/{lessonExercise}/attempts/{attempt}/save', [StudentExerciseController::class, 'save'])->name('exercises.save');
    Route::post('exercises/{lessonExercise}/attempts/{attempt}/submit', [StudentExerciseController::class, 'submit'])->name('exercises.submit');
    Route::get('exercises/{lessonExercise}/attempts/{attempt}/result', [StudentExerciseController::class, 'result'])->name('exercises.result');
    Route::get('exams', [StudentExamController::class, 'index'])->name('exams');
    Route::get('exams/{exam}', [StudentExamController::class, 'show'])->name('exams.show');
    Route::post('exams/{exam}', [StudentExamController::class, 'store'])->name('exams.store');
    Route::post('exams/{exam}/store', [StudentExamController::class, 'store'])->name('exams.autosave');
    Route::post('exams/{exam}/submit', [StudentExamController::class, 'submit'])->name('exams.submit');
    Route::get('exams/{exam}/results', [StudentExamController::class, 'results'])->name('exams.results');
    Route::get('students', [PrefectStudentController::class, 'index'])->name('students');
    Route::get('students/{student}', [PrefectStudentController::class, 'show'])->name('students.show');
    Route::get('students/{student}/edit', [PrefectStudentController::class, 'edit'])->name('students.edit');
    Route::put('students/{student}', [PrefectStudentController::class, 'update'])->name('students.update');
});

// Student Routes. Prefects keep their own dashboard, but can use the same
// student academic and personal tools because prefects are also students.
Route::middleware(['auth', 'role:student,prefect'])->prefix('student')->name('student.')->group(function () {
    Route::get('dashboard', [StudentDashboard::class, 'index'])->name('dashboard');
    Route::get('lesson-notes', [StudentLessonNoteController::class, 'index'])->name('lesson-notes.index');
    Route::get('lesson-notes/{lessonNote}', [StudentLessonNoteController::class, 'show'])->name('lesson-notes.show');
    Route::get('exercises', [StudentExerciseController::class, 'index'])->name('exercises.index');
    Route::get('exercises/{lessonExercise}', [StudentExerciseController::class, 'show'])->name('exercises.show');
    Route::post('exercises/{lessonExercise}/attempts/{attempt}/save', [StudentExerciseController::class, 'save'])->name('exercises.save');
    Route::post('exercises/{lessonExercise}/attempts/{attempt}/submit', [StudentExerciseController::class, 'submit'])->name('exercises.submit');
    Route::get('exercises/{lessonExercise}/attempts/{attempt}/result', [StudentExerciseController::class, 'result'])->name('exercises.result');
    Route::get('exams', [StudentExamController::class, 'index'])->name('exams');
    Route::get('exams/{exam}', [StudentExamController::class, 'show'])->name('exams.show');
    Route::post('exams/{exam}', [StudentExamController::class, 'store'])->name('exams.store');
    Route::post('exams/{exam}/store', [StudentExamController::class, 'store'])->name('exams.autosave');
    Route::post('exams/{exam}/submit', [StudentExamController::class, 'submit'])->name('exams.submit');
    Route::get('exams/{exam}/results', [StudentExamController::class, 'results'])->name('exams.results');
    Route::get('payments', [StudentDashboard::class, 'payments'])->name('payments');
    Route::get('attendance', [StudentDashboard::class, 'attendance'])->name('attendance');
    Route::get('directory/students', [StudentDirectoryController::class, 'students'])->name('directory.students');
    Route::get('directory/students/{student}', [StudentDirectoryController::class, 'student'])->name('directory.student');
    Route::get('profile', [StudentProfileController::class, 'edit'])->name('profile.edit');
    Route::put('profile', [StudentProfileController::class, 'update'])->name('profile.update');
    Route::get('requests', [StudentRequestController::class, 'index'])->name('requests');
    Route::post('requests', [StudentRequestController::class, 'store'])->name('requests.store');
});

// Common Routes (for all authenticated users)
Route::middleware('auth')->group(function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::get('traffic', [TrafficAnalyticsController::class, 'index'])->name('traffic.index');
    Route::get('traffic/data', [TrafficAnalyticsController::class, 'data'])->name('traffic.data');
    Route::get('academic-sessions', [AcademicSessionController::class, 'index'])->name('academic-sessions.index');
    Route::post('academic-sessions', [AcademicSessionController::class, 'store'])->name('academic-sessions.store');
    Route::put('academic-sessions/{academicSession}', [AcademicSessionController::class, 'update'])->name('academic-sessions.update');
    Route::patch('academic-sessions/{academicSession}/activate', [AcademicSessionController::class, 'activate'])->name('academic-sessions.activate');
    Route::get('student-roles', [StudentRoleController::class, 'index'])->name('student-roles.index');
    Route::post('student-roles', [StudentRoleController::class, 'store'])->name('student-roles.store');
    Route::put('student-roles/{studentRole}', [StudentRoleController::class, 'update'])->name('student-roles.update');
    Route::delete('student-roles/{studentRole}', [StudentRoleController::class, 'destroy'])->name('student-roles.destroy');
    Route::get('prefect-roles', [PrefectRoleController::class, 'index'])->name('prefect-roles.index');
    Route::post('prefect-roles', [PrefectRoleController::class, 'store'])->name('prefect-roles.store');
    Route::put('prefect-roles/{prefectRole}', [PrefectRoleController::class, 'update'])->name('prefect-roles.update');
    Route::delete('prefect-roles/{prefectRole}', [PrefectRoleController::class, 'destroy'])->name('prefect-roles.destroy');
});
